#pragma once

#include <cstddef>
#include <cstdint>

// is single frame flashed as base image or the animation used as default display
#define USE_ANIMATION 1


#if USE_ANIMATION
#include "imagesVideos/forst_walkTrim_128x256_anim.h"
#define FLASHED_IMAGE_DATA GENERATED_ANIMATION_DATA
#define ANIMATION_FRAME_DELAY_MS GENERATED_ANIMATION_FRAME_DELAY_MS
#define ANIMATION_FRAME_COUNT GENERATED_ANIMATION_FRAME_COUNT
#else
#include "imagesVideos/apple_128x256ByteArray.h"
#define FLASHED_IMAGE_DATA GENERATED_IMAGE_DATA
#define ANIMATION_FRAME_DELAY_MS 0
#endif

#define LOGICAL_IMAGE_WIDTH 128
#define LOGICAL_IMAGE_HEIGHT 256
#define LOGICAL_PANEL_COUNT_X 2
#define LOGICAL_PANEL_COUNT_Y 2
#define LOGICAL_PANEL_WIDTH 64
#define LOGICAL_PANEL_HEIGHT 128
#define PHYSICAL_PANEL_WIDTH 128
#define PHYSICAL_PANEL_HEIGHT 64
#define FIRST_FLIPPED_PANEL_INDEX 2
#define IMAGE_BYTES_PER_PIXEL 3
#define LOGICAL_PIXEL_COUNT (LOGICAL_IMAGE_WIDTH * LOGICAL_IMAGE_HEIGHT)
#define FRAME_BUFFER_SIZE_BYTES (LOGICAL_PIXEL_COUNT * sizeof(uint32_t))
#define SOURCE_FRAME_SIZE_BYTES (LOGICAL_PIXEL_COUNT * IMAGE_BYTES_PER_PIXEL)
#define IMAGE_GREEN_BYTE_OFFSET 0
#define IMAGE_BLUE_BYTE_OFFSET 1
#define IMAGE_RED_BYTE_OFFSET 2
#define BLACK_COLOR_VALUE 0
#define SYSTEM_CLOCK_KHZ 250000
#define DISPLAY_BASE_BRIGHTNESS 40
#define DISPLAY_INTENSITY 0.8f
#define FIRST_FRAME_INDEX 0
#define MINIMUM_FRAME_COUNT 1
#define FRAME_INDEX_STEP 1
#define UPLOAD_ACK_MESSAGE "ACK\n"
#define STARTUP_DELAY_5S 5000
#define UPLOAD_POLL_DELAY_1MS 1
#define FPS_UPDATE_INTERVAL_1S 1000
#define STATUS_PRINT_INTERVAL_10S 10000
#define WIFI_CONNECT_TIMEOUT_MS 15000
#define WIFI_RETRY_INTERVAL_MS 10000
#define TCP_BIND_RETRY_INTERVAL_MS 2000
#define WIFI_HEALTH_CHECK_INTERVAL_MS 2000
#define RSSI_PROBE_FAIL_DEBOUNCE_COUNT 3
#define WIFI_GATEWAY_PROBE_INTERVAL_MS 5000
#define WIFI_GATEWAY_PROBE_TIMEOUT_MS 3000
#define WIFI_GATEWAY_PROBE_FAIL_DEBOUNCE_COUNT 3
#define WIFI_ICON_WIDTH 8
#define WIFI_ICON_HEIGHT 8
#define WIFI_ICON_MARGIN 2
#define WIFI_ICON_HORIZONTAL_OFFSET 1
#define WIFI_ICON_BACKING_SIDE_PADDING 1
#define WIFI_ICON_BACKING_WIDTH (WIFI_ICON_WIDTH + (2 * WIFI_ICON_BACKING_SIDE_PADDING))
#define WIFI_ICON_BACKING_HEIGHT WIFI_ICON_HEIGHT + 1
#define WIFI_ICON_BAR_COUNT 3
#define WIFI_ICON_BAR_WIDTH 2
#define WIFI_ICON_BAR_HEIGHT_STEP 2
#define WIFI_ICON_BAR_COLUMN_STEP 3

// Visual panels in row/column order mapped to their daisy-chain panel indices.
static const int PANEL_INDEX_BY_LOGICAL_PANEL[LOGICAL_PANEL_COUNT_Y][LOGICAL_PANEL_COUNT_X] = {{2, 1}, {3, 0}};
